# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\kobe_doc\code\github\python\laser_proj\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LaserMainWindow(object):
    def setupUi(self, LaserMainWindow):
        LaserMainWindow.setObjectName("LaserMainWindow")
        LaserMainWindow.resize(1478, 1046)
        self.centralwidget = QtWidgets.QWidget(LaserMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(40, 780, 381, 61))
        self.pushButton_start.setObjectName("pushButton_start")
        self.tableWidget_print_list = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_print_list.setGeometry(QtCore.QRect(730, 120, 741, 881))
        self.tableWidget_print_list.setShowGrid(True)
        self.tableWidget_print_list.setRowCount(3)
        self.tableWidget_print_list.setObjectName("tableWidget_print_list")
        self.tableWidget_print_list.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_print_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_print_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_print_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_print_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_print_list.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_print_list.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_print_list.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_print_list.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_print_list.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_print_list.setItem(2, 1, item)
        self.tableWidget_print_list.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget_print_list.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_print_list.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_print_list.verticalHeader().setDefaultSectionSize(80)
        self.pushButton_edit_item = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_edit_item.setGeometry(QtCore.QRect(220, 850, 201, 51))
        self.pushButton_edit_item.setObjectName("pushButton_edit_item")
        self.pushButton_create_table = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_create_table.setGeometry(QtCore.QRect(40, 850, 171, 51))
        self.pushButton_create_table.setObjectName("pushButton_create_table")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(40, 910, 381, 61))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 680, 51, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 290, 71, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 680, 71, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 580, 101, 31))
        self.label_5.setObjectName("label_5")
        self.checkBox_select_all = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_select_all.setGeometry(QtCore.QRect(770, 70, 101, 31))
        self.checkBox_select_all.setChecked(False)
        self.checkBox_select_all.setTristate(False)
        self.checkBox_select_all.setObjectName("checkBox_select_all")
        self.checkBox_select_unprint = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_select_unprint.setGeometry(QtCore.QRect(1060, 70, 121, 31))
        self.checkBox_select_unprint.setObjectName("checkBox_select_unprint")
        self.checkBox_select_invert = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_select_invert.setGeometry(QtCore.QRect(920, 70, 101, 31))
        self.checkBox_select_invert.setObjectName("checkBox_select_invert")
        self.comboBox_select_items = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_select_items.setGeometry(QtCore.QRect(150, 580, 271, 41))
        self.comboBox_select_items.setObjectName("comboBox_select_items")
        self.comboBox_select_items.addItem("")
        self.pushButton_select_excel_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_select_excel_file.setGeometry(QtCore.QRect(30, 380, 101, 41))
        self.pushButton_select_excel_file.setObjectName("pushButton_select_excel_file")
        self.pushButton_deal_excel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_deal_excel.setGeometry(QtCore.QRect(40, 500, 381, 46))
        self.pushButton_deal_excel.setObjectName("pushButton_deal_excel")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 10, 151, 31))
        self.label_6.setObjectName("label_6")
        self.textEdit_product_file = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_product_file.setGeometry(QtCore.QRect(150, 390, 271, 31))
        self.textEdit_product_file.setObjectName("textEdit_product_file")
        self.textEdit_operator_name = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_operator_name.setGeometry(QtCore.QRect(130, 290, 171, 31))
        self.textEdit_operator_name.setText("")
        self.textEdit_operator_name.setObjectName("textEdit_operator_name")
        self.label_custom_file = QtWidgets.QLabel(self.centralwidget)
        self.label_custom_file.setGeometry(QtCore.QRect(260, 10, 891, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_custom_file.setFont(font)
        self.label_custom_file.setObjectName("label_custom_file")
        self.textEdit_begin_num = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_begin_num.setGeometry(QtCore.QRect(110, 680, 51, 31))
        self.textEdit_begin_num.setObjectName("textEdit_begin_num")
        self.textEdit_end_num = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_end_num.setGeometry(QtCore.QRect(240, 680, 51, 31))
        self.textEdit_end_num.setObjectName("textEdit_end_num")
        self.pushButton_filter_num = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_filter_num.setGeometry(QtCore.QRect(310, 670, 101, 51))
        self.pushButton_filter_num.setObjectName("pushButton_filter_num")
        self.label_total_num = QtWidgets.QLabel(self.centralwidget)
        self.label_total_num.setGeometry(QtCore.QRect(30, 640, 251, 24))
        self.label_total_num.setObjectName("label_total_num")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 330, 71, 31))
        self.label_7.setObjectName("label_7")
        self.textEdit_custom_name = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_custom_name.setGeometry(QtCore.QRect(130, 330, 171, 31))
        self.textEdit_custom_name.setText("")
        self.textEdit_custom_name.setObjectName("textEdit_custom_name")
        self.progressBar_print = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_print.setEnabled(True)
        self.progressBar_print.setGeometry(QtCore.QRect(30, 100, 391, 51))
        self.progressBar_print.setMaximum(50)
        self.progressBar_print.setProperty("value", 50)
        self.progressBar_print.setTextVisible(True)
        self.progressBar_print.setObjectName("progressBar_print")
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setEnabled(False)
        self.pushButton_stop.setGeometry(QtCore.QRect(30, 180, 311, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_stop.sizePolicy().hasHeightForWidth())
        self.pushButton_stop.setSizePolicy(sizePolicy)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.comboBox_select_custom = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_select_custom.setGeometry(QtCore.QRect(320, 330, 121, 31))
        self.comboBox_select_custom.setObjectName("comboBox_select_custom")
        self.comboBox_select_custom.addItem("")
        self.comboBox_select_operator = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_select_operator.setGeometry(QtCore.QRect(320, 290, 121, 31))
        self.comboBox_select_operator.setObjectName("comboBox_select_operator")
        self.comboBox_select_operator.addItem("")
        self.tableWidget_combo_select = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_combo_select.setEnabled(False)
        self.tableWidget_combo_select.setGeometry(QtCore.QRect(450, 170, 241, 831))
        self.tableWidget_combo_select.setShowGrid(True)
        self.tableWidget_combo_select.setRowCount(3)
        self.tableWidget_combo_select.setObjectName("tableWidget_combo_select")
        self.tableWidget_combo_select.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_combo_select.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_combo_select.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_combo_select.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_combo_select.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_combo_select.setItem(2, 0, item)
        self.tableWidget_combo_select.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget_combo_select.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_combo_select.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_combo_select.verticalHeader().setDefaultSectionSize(80)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(700, 120, 16, 881))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.checkBox_group_print = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_group_print.setGeometry(QtCore.QRect(470, 110, 131, 31))
        self.checkBox_group_print.setChecked(False)
        self.checkBox_group_print.setTristate(False)
        self.checkBox_group_print.setObjectName("checkBox_group_print")
        self.textEdit_output_path = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_output_path.setGeometry(QtCore.QRect(150, 430, 271, 31))
        self.textEdit_output_path.setObjectName("textEdit_output_path")
        self.pushButton_select_output_path = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_select_output_path.setGeometry(QtCore.QRect(30, 420, 101, 41))
        self.pushButton_select_output_path.setObjectName("pushButton_select_output_path")
        self.textEdit_stop_index = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_stop_index.setEnabled(False)
        self.textEdit_stop_index.setGeometry(QtCore.QRect(350, 190, 51, 41))
        self.textEdit_stop_index.setObjectName("textEdit_stop_index")
        LaserMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LaserMainWindow)
        self.statusbar.setObjectName("statusbar")
        LaserMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LaserMainWindow)
        self.pushButton_exit.clicked.connect(LaserMainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(LaserMainWindow)

    def retranslateUi(self, LaserMainWindow):
        _translate = QtCore.QCoreApplication.translate
        LaserMainWindow.setWindowTitle(_translate("LaserMainWindow", "MainWindow"))
        self.pushButton_start.setText(_translate("LaserMainWindow", "开始"))
        item = self.tableWidget_print_list.horizontalHeaderItem(0)
        item.setText(_translate("LaserMainWindow", "序号"))
        item = self.tableWidget_print_list.horizontalHeaderItem(1)
        item.setText(_translate("LaserMainWindow", "原序号"))
        item = self.tableWidget_print_list.horizontalHeaderItem(2)
        item.setText(_translate("LaserMainWindow", "状态"))
        item = self.tableWidget_print_list.horizontalHeaderItem(3)
        item.setText(_translate("LaserMainWindow", "名称"))
        __sortingEnabled = self.tableWidget_print_list.isSortingEnabled()
        self.tableWidget_print_list.setSortingEnabled(False)
        item = self.tableWidget_print_list.item(0, 0)
        item.setText(_translate("LaserMainWindow", "1"))
        item = self.tableWidget_print_list.item(0, 1)
        item.setText(_translate("LaserMainWindow", "12"))
        item = self.tableWidget_print_list.item(0, 2)
        item.setText(_translate("LaserMainWindow", "已打印"))
        item = self.tableWidget_print_list.item(0, 3)
        item.setText(_translate("LaserMainWindow", "THYJJJ12121KKKwewewK"))
        self.tableWidget_print_list.setSortingEnabled(__sortingEnabled)
        self.pushButton_edit_item.setText(_translate("LaserMainWindow", "编辑信息"))
        self.pushButton_create_table.setText(_translate("LaserMainWindow", "生成报表"))
        self.pushButton_exit.setText(_translate("LaserMainWindow", "退出"))
        self.label_2.setText(_translate("LaserMainWindow", "结束"))
        self.label_3.setText(_translate("LaserMainWindow", "操作员"))
        self.label_4.setText(_translate("LaserMainWindow", "开始"))
        self.label_5.setText(_translate("LaserMainWindow", "打印条目"))
        self.checkBox_select_all.setText(_translate("LaserMainWindow", "全选"))
        self.checkBox_select_unprint.setText(_translate("LaserMainWindow", "未打印"))
        self.checkBox_select_invert.setText(_translate("LaserMainWindow", "反选"))
        self.comboBox_select_items.setItemText(0, _translate("LaserMainWindow", "空"))
        self.pushButton_select_excel_file.setText(_translate("LaserMainWindow", "浏览文件"))
        self.pushButton_deal_excel.setText(_translate("LaserMainWindow", "导入文件"))
        self.label_6.setText(_translate("LaserMainWindow", "制作 by kobe"))
        self.textEdit_product_file.setText(_translate("LaserMainWindow", "客户.xls"))
        self.label_custom_file.setText(_translate("LaserMainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">客户文件信息:空</span></p></body></html>"))
        self.textEdit_begin_num.setText(_translate("LaserMainWindow", "1"))
        self.textEdit_end_num.setText(_translate("LaserMainWindow", "1"))
        self.pushButton_filter_num.setText(_translate("LaserMainWindow", "选择"))
        self.label_total_num.setText(_translate("LaserMainWindow", "总条数目： 0"))
        self.label_7.setText(_translate("LaserMainWindow", "客户名"))
        self.progressBar_print.setFormat(_translate("LaserMainWindow", "进度: 0/0"))
        self.pushButton_stop.setText(_translate("LaserMainWindow", "停止"))
        self.comboBox_select_custom.setItemText(0, _translate("LaserMainWindow", "空"))
        self.comboBox_select_operator.setItemText(0, _translate("LaserMainWindow", "空"))
        item = self.tableWidget_combo_select.horizontalHeaderItem(0)
        item.setText(_translate("LaserMainWindow", "序号"))
        item = self.tableWidget_combo_select.horizontalHeaderItem(1)
        item.setText(_translate("LaserMainWindow", "名称"))
        __sortingEnabled = self.tableWidget_combo_select.isSortingEnabled()
        self.tableWidget_combo_select.setSortingEnabled(False)
        self.tableWidget_combo_select.setSortingEnabled(__sortingEnabled)
        self.checkBox_group_print.setText(_translate("LaserMainWindow", "打印组"))
        self.textEdit_output_path.setText(_translate("LaserMainWindow", "C:\\"))
        self.pushButton_select_output_path.setText(_translate("LaserMainWindow", "导出路径"))
        self.textEdit_stop_index.setText(_translate("LaserMainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LaserMainWindow = QtWidgets.QMainWindow()
    ui = Ui_LaserMainWindow()
    ui.setupUi(LaserMainWindow)
    LaserMainWindow.show()
    sys.exit(app.exec_())

