# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\kobe_doc\code\github\python\laser_proj\ui\main_window_solt.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LaserMainWindow(object):
    def setupUi(self, LaserMainWindow):
        LaserMainWindow.setObjectName("LaserMainWindow")
        LaserMainWindow.resize(1223, 1070)
        self.centralwidget = QtWidgets.QWidget(LaserMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(40, 690, 381, 61))
        self.pushButton_start.setObjectName("pushButton_start")
        self.tableWidget_print_list = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_print_list.setGeometry(QtCore.QRect(440, 120, 741, 881))
        self.tableWidget_print_list.setShowGrid(True)
        self.tableWidget_print_list.setRowCount(3)
        self.tableWidget_print_list.setObjectName("tableWidget_print_list")
        self.tableWidget_print_list.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_print_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_print_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_print_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_print_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_print_list.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_print_list.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_print_list.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_print_list.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_print_list.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_print_list.setItem(2, 1, item)
        self.tableWidget_print_list.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget_print_list.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_print_list.verticalHeader().setDefaultSectionSize(59)
        self.pushButton_mix_table = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_mix_table.setGeometry(QtCore.QRect(220, 760, 201, 51))
        self.pushButton_mix_table.setObjectName("pushButton_mix_table")
        self.pushButton_create_table = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_create_table.setGeometry(QtCore.QRect(40, 760, 171, 51))
        self.pushButton_create_table.setObjectName("pushButton_create_table")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(40, 820, 381, 61))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 600, 51, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 310, 71, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 600, 71, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 540, 101, 31))
        self.label_5.setObjectName("label_5")
        self.comboBox_start_index = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_start_index.setGeometry(QtCore.QRect(150, 600, 71, 31))
        self.comboBox_start_index.setObjectName("comboBox_start_index")
        self.comboBox_start_index.addItem("")
        self.comboBox_end_index = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_end_index.setGeometry(QtCore.QRect(340, 600, 81, 31))
        self.comboBox_end_index.setObjectName("comboBox_end_index")
        self.comboBox_end_index.addItem("")
        self.checkBox_select_all = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_select_all.setGeometry(QtCore.QRect(480, 70, 101, 31))
        self.checkBox_select_all.setObjectName("checkBox_select_all")
        self.checkBox_select_unprint = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_select_unprint.setGeometry(QtCore.QRect(770, 70, 121, 31))
        self.checkBox_select_unprint.setObjectName("checkBox_select_unprint")
        self.checkBox_select_invert = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_select_invert.setGeometry(QtCore.QRect(630, 70, 101, 31))
        self.checkBox_select_invert.setObjectName("checkBox_select_invert")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(20, 30, 401, 211))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.comboBox_select_items = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_select_items.setGeometry(QtCore.QRect(150, 540, 271, 41))
        self.comboBox_select_items.setObjectName("comboBox_select_items")
        self.comboBox_select_items.addItem("")
        self.pushButton_select_excel_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_select_excel_file.setGeometry(QtCore.QRect(30, 380, 101, 41))
        self.pushButton_select_excel_file.setObjectName("pushButton_select_excel_file")
        self.pushButton_deal_excel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_deal_excel.setGeometry(QtCore.QRect(40, 450, 381, 46))
        self.pushButton_deal_excel.setObjectName("pushButton_deal_excel")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 10, 151, 31))
        self.label_6.setObjectName("label_6")
        self.textEdit_product_file = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_product_file.setGeometry(QtCore.QRect(150, 390, 271, 31))
        self.textEdit_product_file.setObjectName("textEdit_product_file")
        self.textEdit_operator_name = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_operator_name.setGeometry(QtCore.QRect(150, 310, 261, 31))
        self.textEdit_operator_name.setObjectName("textEdit_operator_name")
        LaserMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LaserMainWindow)
        self.statusbar.setObjectName("statusbar")
        LaserMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LaserMainWindow)
        QtCore.QMetaObject.connectSlotsByName(LaserMainWindow)

    def retranslateUi(self, LaserMainWindow):
        _translate = QtCore.QCoreApplication.translate
        LaserMainWindow.setWindowTitle(_translate("LaserMainWindow", "MainWindow"))
        self.pushButton_start.setText(_translate("LaserMainWindow", "开始"))
        item = self.tableWidget_print_list.horizontalHeaderItem(0)
        item.setText(_translate("LaserMainWindow", "序号"))
        item = self.tableWidget_print_list.horizontalHeaderItem(1)
        item.setText(_translate("LaserMainWindow", "原序号"))
        item = self.tableWidget_print_list.horizontalHeaderItem(2)
        item.setText(_translate("LaserMainWindow", "状态"))
        item = self.tableWidget_print_list.horizontalHeaderItem(3)
        item.setText(_translate("LaserMainWindow", "名称"))
        __sortingEnabled = self.tableWidget_print_list.isSortingEnabled()
        self.tableWidget_print_list.setSortingEnabled(False)
        item = self.tableWidget_print_list.item(0, 0)
        item.setText(_translate("LaserMainWindow", "1"))
        item = self.tableWidget_print_list.item(0, 1)
        item.setText(_translate("LaserMainWindow", "12"))
        item = self.tableWidget_print_list.item(0, 2)
        item.setText(_translate("LaserMainWindow", "已打印"))
        item = self.tableWidget_print_list.item(0, 3)
        item.setText(_translate("LaserMainWindow", "THYJJJ12121KKKK"))
        self.tableWidget_print_list.setSortingEnabled(__sortingEnabled)
        self.pushButton_mix_table.setText(_translate("LaserMainWindow", "合并报表"))
        self.pushButton_create_table.setText(_translate("LaserMainWindow", "生成报表"))
        self.pushButton_exit.setText(_translate("LaserMainWindow", "退出"))
        self.label_2.setText(_translate("LaserMainWindow", "结束"))
        self.label_3.setText(_translate("LaserMainWindow", "操作员"))
        self.label_4.setText(_translate("LaserMainWindow", "开始"))
        self.label_5.setText(_translate("LaserMainWindow", "打印条目"))
        self.comboBox_start_index.setItemText(0, _translate("LaserMainWindow", "1"))
        self.comboBox_end_index.setItemText(0, _translate("LaserMainWindow", "1"))
        self.checkBox_select_all.setText(_translate("LaserMainWindow", "全选"))
        self.checkBox_select_unprint.setText(_translate("LaserMainWindow", "未打印"))
        self.checkBox_select_invert.setText(_translate("LaserMainWindow", "反选"))
        self.label_status.setText(_translate("LaserMainWindow", "正在打印状态"))
        self.comboBox_select_items.setItemText(0, _translate("LaserMainWindow", "空"))
        self.pushButton_select_excel_file.setText(_translate("LaserMainWindow", "浏览文件"))
        self.pushButton_deal_excel.setText(_translate("LaserMainWindow", "导入"))
        self.label_6.setText(_translate("LaserMainWindow", "制作 by kobe"))
        self.textEdit_product_file.setText(_translate("LaserMainWindow", "客户.xls"))
        self.textEdit_operator_name.setText(_translate("LaserMainWindow", "张三"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LaserMainWindow = QtWidgets.QMainWindow()
    ui = Ui_LaserMainWindow()
    ui.setupUi(LaserMainWindow)
    LaserMainWindow.show()
    sys.exit(app.exec_())

